### ISSUE TITLE
Неправильно работают комментарии

### ISSUE THREAD

**Issue by KostikShutov** [Urezzzer/compiler#4]
В errors.txt пишется
```
ERROR                INDEX_TOKEN             

ErrorTypes.NOT_VALID     LexerToken.NOT_EXISTS   
```
на следующий кейс
```
int main()
{
    // $^/int a0 = 0 + 0;
}
```
По идее этой кейс должен был отработать корректно, т.к single комментарий подразумевает игнорирование всего, что находится справа

**Comment by TureevS** [comment]
Решено
